### ISSUE TITLE
img_to_pickleがError

### ISSUE THREAD

**Issue by haisland0909** [haisland0909/Denoising-Dirty-Documents#1]
No such file or directoryだそうです。

**Comment by guruttosekai2011** [comment]
raw dataのところにダウンロードデータ入れないといけないんです（自動で同意させれなかったのでそこだけ手動です）が、それ以外のところで出てしまいますか？

**Comment by haisland0909** [comment]
load dataのとこだけ1行直したよ
ディレクトリ構造変更したからそれに合ってなかった

**Comment by haisland0909** [comment]
したら最後まで流れた

**Comment by guruttosekai2011** [comment]
なるほどです！
ありがとうございます

**Comment by haisland0909** [comment]
念のためなんだけど、TrainとClean_trainのArrayの画像が同じ順序でImportできてるか確認する処理追加しておいてほしい。
名前のリストにどんどんAppendしていって最後にListの中身が一致してるかどうかとかで十分です。

**Comment by haisland0909** [comment]
もしくはデータの形状をArrayのDictにするか、これなら確認処理はなくてもいい

**Comment by haisland0909** [comment]
これCloseするんで、新しいIssue自分でたてて作業してみて、
コミットメッセージに #Issue番号付けるとIssueとコミットが関連付けられます。
