### ISSUE TITLE
labelをclean_gray_dataからlabelデータに変更

### ISSUE THREAD

**Issue by haisland0909** [haisland0909/Denoising-Dirty-Documents#12]
load_dataを変更すればいいかも

**Comment by guruttosekai2011** [comment]
ネット断食してました
labelsの作るところ、修正してくださったんですね。
img_to_pickle.py のロードにlabelsを追加し、他２ファイルのロードしている部分にもlablesを追加しました。

**Comment by guruttosekai2011** [comment]
すいません。さっきのできてなかったので再度修正してpushします
