### ISSUE TITLE
評価方法をmean_absolute_errorに変更

### ISSUE THREAD

**Issue by haisland0909** [haisland0909/Denoising-Dirty-Documents#14]
Kaggleの評価方法に併せてmean_absolute_errorに変更する。

**Comment by haisland0909** [comment]
[165.61196210642473, 164.84479418547258, 161.38123260110862, 165.05555771007869, 166.24610168702961]
Score_Average: 164.627929658
とかありえない数値になってしまった、set_train_dataとset_valid_dataのせいっぽい？

**Comment by guruttosekai2011** [comment]
どうやら、その通りでした。
labelデータは前回直していただいたので 0~1 です。
train_dataに関してはpartial_fitを使うために preprocessing.StandardScaler() を用いて 0~1 に正規化したのに対し、
valid_dataでは正規化をしていないため、入力が 0~255 になったままだったため、予測がtrain_dataに対して大幅に大きくなり、ありえない数値になったかと思います。

**Comment by guruttosekai2011** [comment]
preprocessing.StandardScaler() を追加してるので、動作確認してpushします

**Comment by guruttosekai2011** [comment]
[0.058931300089892787, 0.058473869509438746, 0.063740562972101289, 0.057393982518324803, 0.060603608707077691]
Score_Average: 0.0598286647594

やはり、それが原因でした。
この成績だったら40番台（128人中）ですね
