### ISSUE TITLE
Clean Imageはバイナリで

### ISSUE THREAD

**Issue by haisland0909** [haisland0909/Denoising-Dirty-Documents#3]
今Cleanなイメージもグレースケールで出力してるのでラベルデータとしてほしいのでバイナリにしてもらいたいです

**Comment by guruttosekai2011** [comment]
そこについて相談させていただきたかったのですが、正解ラベルの閾値をどうしましょうか？
ちゃんと見てみると境界部分などにおいて、文字のエッジ部分などで中間色があり、255で切ると確実に答えラベルで精度が変わるような気がします。

2.png とかの画像をみると、文字まわりがうっすらと薄い灰色で枠取られていたりするのですが、これを無視する領域だとすると150とか128(半分)くらいなのかな？と考えるのですが、いかがですか？

**Comment by guruttosekai2011** [comment]
img_to_pickle.py
にバイナリで作る部分を一応実装したので、closeします。
