### ISSUE TITLE
[feature] 画像の端点かどうか

### ISSUE THREAD

**Issue by haisland0909** [haisland0909/Denoising-Dirty-Documents#6]
なんとなく効きそう

**Comment by guruttosekai2011** [comment]
これは効くと思います。
アイデアベースですが、文字の位置という意味では、字の上下幅は等しくなっているので、下のラインと上のラインをなんらかの形で与えてやれれば良いかもしれません。

**Comment by haisland0909** [comment]
[0.41427480471855793, 0.45955913889406086, 0.45369569044651747, 0.46181920218033801, 0.38313544745445893]
Score_Average: 0.434496856739
